### ISSUE TITLE
phpmyadmin not working

### ISSUE THREAD

**Issue by fe3dback** [cytopia/devilbox#64]
now adminer is ok, phpmyadmin is not.

containers:
```
9de540fcb0cd        cytopia/mysql-5.7:0.9     "/docker-entrypoin..."   5 hours ago         Up 5 hours          127.0.0.1:3306->3306/tcp                     devilbox_mysql_1
4bdbec57bd5c        cytopia/apache-2.4:0.9    "/docker-entrypoin..."   5 hours ago         Up 5 hours          127.0.0.1:80->80/tcp                         devilbox_httpd_1
a2d7362d18e1        cytopia/php-fpm-7.0:0.9   "/docker-entrypoin..."   5 hours ago         Up 5 hours          9000/tcp                                     devilbox_php_1
cf1aed406f1a        cytopia/bind:latest       "/docker-entrypoin..."   5 hours ago         Up 5 hours          127.0.0.1:54->53/tcp, 127.0.0.1:54->53/udp   devilbox_bind_1
```

http://127.0.0.1/vendor/phpmyadmin-4.7/index.php

```
( ! ) Fatal error: Uncaught UnexpectedValueException: Overloading of string functions using mbstring.func_overload is not supported by phpseclib. in /var/www/default/htdocs/vendor/phpmyadmin-4.7/vendor/phpseclib/phpseclib/phpseclib/bootstrap.php on line 11
( ! ) UnexpectedValueException: Overloading of string functions using mbstring.func_overload is not supported by phpseclib. in /var/www/default/htdocs/vendor/phpmyadmin-4.7/vendor/phpseclib/phpseclib/phpseclib/bootstrap.php on line 11
Call Stack
#	Time	Memory	Function	Location
1	0.0001	376512	{main}( )	.../index.php:0
2	0.0001	383984	require_once( '/var/www/default/htdocs/vendor/phpmyadmin-4.7/libraries/common.inc.php' )	.../index.php:19
3	0.0001	384992	require_once( '/var/www/default/htdocs/vendor/phpmyadmin-4.7/vendor/autoload.php' )	.../common.inc.php:85
4	0.0002	385648	ComposerAutoloaderInit7033babd32da3410d35a338a5cac8c30::getLoader( )	.../autoload.php:7
5	0.0004	392216	composerRequire7033babd32da3410d35a338a5cac8c30( )	.../autoload_real.php:60
6	0.0004	392464	require( '/var/www/default/htdocs/vendor/phpmyadmin-4.7/vendor/phpseclib/phpseclib/phpseclib/bootstrap.php' )	.../autoload_real.php:70
```

my conf, version, etc still same from #61

**Comment by cytopia** [comment]
I am using the same container:
```shell
docker ps
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                                        NAMES
6be2188710ae        cytopia/mysql-5.7:0.9       "/docker-entrypoin..."   2 minutes ago       Up 2 minutes        127.0.0.1:3306->3306/tcp                     devilbox_mysql_1
089b793a5e4c        cytopia/apache-2.4:0.9      "/docker-entrypoin..."   2 minutes ago       Up 2 minutes        127.0.0.1:80->80/tcp                         devilbox_httpd_1
140c55cfec8e        cytopia/php-fpm-7.0:0.9     "/docker-entrypoin..."   2 minutes ago       Up 2 minutes        9000/tcp                                     devilbox_php_1
0fd5e2b4134e        cytopia/bind:latest         "/docker-entrypoin..."   2 minutes ago       Up 2 minutes        127.0.0.1:53->53/tcp, 127.0.0.1:53->53/udp   devilbox_bind_1
```

No exceptions here...


How about: http://127.0.0.1/vendor/phpmyadmin-4.0 ?
(Ignore the php warnings, will only be offered for php-5.4 anyway)

**Comment by fe3dback** [comment]
![screenshot from 2017-05-24 15-58-52](https://cloud.githubusercontent.com/assets/2073883/26404278/fcd0a31c-4099-11e7-8b25-9f379288ab4f.png)

```
( ! ) Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; StringReader has a deprecated constructor in /var/www/default/htdocs/vendor/phpmyadmin-4.0/libraries/php-gettext/streams.php on line 48
Call Stack
#	Time	Memory	Function	Location
1	0.0015	377776	{main}( )	.../index.php:0
2	0.0142	385344	require_once( '/var/www/default/htdocs/vendor/phpmyadmin-4.0/libraries/common.inc.php' )	.../index.php:11
3	0.1587	754032	require( '/var/www/default/htdocs/vendor/phpmyadmin-4.0/libraries/select_lang.lib.php' )	.../common.inc.php:583
4	0.1605	754784	require_once( '/var/www/default/htdocs/vendor/phpmyadmin-4.0/libraries/php-gettext/gettext.inc' )	.../select_lang.lib.php:395

( ! ) Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; FileReader has a deprecated constructor in /var/www/default/htdocs/vendor/phpmyadmin-4.0/libraries/php-gettext/streams.php on line 84
Call Stack
#	Time	Memory	Function	Location
1	0.0015	377776	{main}( )	.../index.php:0
2	0.0142	385344	require_once( '/var/www/default/htdocs/vendor/phpmyadmin-4.0/libraries/common.inc.php' )	.../index.php:11
3	0.1587	754032	require( '/var/www/default/htdocs/vendor/phpmyadmin-4.0/libraries/select_lang.lib.php' )	.../common.inc.php:583
4	0.1605	754784	require_once( '/var/www/default/htdocs/vendor/phpmyadmin-4.0/libraries/php-gettext/gettext.inc' )	.../select_lang.lib.php:395

( ! ) Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; CachedFileReader has a deprecated constructor in /var/www/default/htdocs/vendor/phpmyadmin-4.0/libraries/php-gettext/streams.php on line 145
Call Stack
#	Time	Memory	Function	Location
1	0.0015	377776	{main}( )	.../index.php:0
2	0.0142	385344	require_once( '/var/www/default/htdocs/vendor/phpmyadmin-4.0/libraries/common.inc.php' )	.../index.php:11
3	0.1587	754032	require( '/var/www/default/htdocs/vendor/phpmyadmin-4.0/libraries/select_lang.lib.php' )	.../common.inc.php:583
4	0.1605	754784	require_once( '/var/www/default/htdocs/vendor/phpmyadmin-4.0/libraries/php-gettext/gettext.inc' )	.../select_lang.lib.php:395

( ! ) Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; gettext_reader has a deprecated constructor in /var/www/default/htdocs/vendor/phpmyadmin-4.0/libraries/php-gettext/gettext.php on line 36
Call Stack
#	Time	Memory	Function	Location
1	0.0015	377776	{main}( )	.../index.php:0
2	0.0142	385344	require_once( '/var/www/default/htdocs/vendor/phpmyadmin-4.0/libraries/common.inc.php' )	.../index.php:11
3	0.1587	754032	require( '/var/www/default/htdocs/vendor/phpmyadmin-4.0/libraries/select_lang.lib.php' )	.../common.inc.php:583
4	0.1605	754784	require_once( '/var/www/default/htdocs/vendor/phpmyadmin-4.0/libraries/php-gettext/gettext.inc' )	.../select_lang.lib.php:395
```

**Comment by cytopia** [comment]
This one is OK. Link will only be active once you enable php-fpm-5.4. Just wanted to double check there.

Could you attach another screenshot from the actual enabled phpMyAdmin version 4.7

**Comment by cytopia** [comment]
**phpMyAdmin 4.0**

Again phpMyAdmin 4.0 errors will appear on later php versions, however it will only be available under the menu if you started up php-fpm-5.4.  So when you open phpMyAdmin 4.0 with php5.4 there will be no errors. So that can be neglected. Just wanted to make double sure here.

**phpMyAdmin 4.7**

Everything above php-5.4 (5.5, 5.6, 7.0, 7.1 and hhvm) should not produce any errors with phpMyAdmin 4.7. I have tried to reproduce this behaviour locally, but did not get any errors.

What exactly did you do on phpMyAdmin 4.7? Or was it just the front-page?

**Comment by fe3dback** [comment]
i use php7.0

when i go here:
http://localhost/vendor/phpmyadmin-4.0/index.php
its look ok, i see login form, and no errors.

when i go here
http://localhost/vendor/phpmyadmin-4.7/index.php
(this url default link from DB menu)
i get erros:
![screenshot from 2017-05-25 12 14 04](https://cloud.githubusercontent.com/assets/2073883/26444111/ac9c4e28-4143-11e7-8eef-f557e840952d.png)

**Comment by cytopia** [comment]
That seems very strange. Could you please provide a few dumps:

* `docker-compose logs`
* `cat log/php-fpm-7.0/php-fpm.err`
* `cat log/php-fpm-7.0/www-error.log`
* `cat log/php-fpm-7.0/www-error.log`
* `cat log/apache-2.4/devilbox-error.log`
* `cat log/apache-2.4/projects-error.log`
* `cat log/apache-2.4/error_log`

**Comment by cytopia** [comment]
Btw, is your git directory clean? (`git status`) and did you check out the current release tag?

**Comment by fe3dback** [comment]
__diff .env env-example__
```
❯ diff .env env-example
110,111c110,111
< HTTPD_SERVER=apache-2.4
< #HTTPD_SERVER=nginx-stable
---
> #HTTPD_SERVER=apache-2.4
> HTTPD_SERVER=nginx-stable
120c120
< MYSQL_SERVER=mysql-5.7
---
> #MYSQL_SERVER=mysql-5.7
124c124
< #MYSQL_SERVER=mariadb-10.1
---
> MYSQL_SERVER=mariadb-10.1
186c186
< HOST_PATH_HTTPD_DATADIR=/home/neo/server
---
> HOST_PATH_HTTPD_DATADIR=./data/www
245c245
< TIMEZONE=Europe/Moscow
---
> TIMEZONE=Europe/Berlin
372c372
< HOST_PORT_BIND=54
---
> HOST_PORT_BIND=53

```

__git status__

```
git status
On branch master
Your branch is behind 'origin/master' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
nothing to commit, working directory clean
```
__docker-compose logs__
```
docker-compose logs
Attaching to devilbox_mysql_1, devilbox_httpd_1, devilbox_php_1, devilbox_bind_1
httpd_1  | [INFO] Setting docker timezone to: Europe/Moscow
httpd_1  | apache $ sudo rm /etc/localtime
httpd_1  | apache $ sudo ln -s /usr/share/zoneinfo/Europe/Moscow /etc/localtime
httpd_1  | [INFO] Docker date set to: Wed May 24 10:13:47 MSK 2017
httpd_1  | [INFO] Enabling PHP-FPM at: php:9000
httpd_1  | apache $ sudo echo '#### PHP-FPM config ####' > /etc/httpd/conf.d/php-fpm.conf
httpd_1  | apache $ sudo echo '' >> /etc/httpd/conf.d/php-fpm.conf
httpd_1  | apache $ sudo echo '# enablereuse' >> /etc/httpd/conf.d/php-fpm.conf
httpd_1  | apache $ sudo echo '# Defining a worker will improve performance' >> /etc/httpd/conf.d/php-fpm.conf
httpd_1  | apache $ sudo echo '# And in this case, re-use the worker (dependent on support from the fcgi application)' >> /etc/httpd/conf.d/php-fpm.conf
httpd_1  | apache $ sudo echo '# If you have enough idle workers, this would only improve the performance marginally' >> /etc/httpd/conf.d/php-fpm.conf
httpd_1  | apache $ sudo echo '#' >> /etc/httpd/conf.d/php-fpm.conf
httpd_1  | apache $ sudo echo '# enablereuse requires Apache 2.4.11 or later' >> /etc/httpd/conf.d/php-fpm.conf
httpd_1  | apache $ sudo echo '#<Proxy "fcgi://172.16.238.11:9000/" enablereuse=on max=10></Proxy>' >> /etc/httpd/conf.d/php-fpm.conf
httpd_1  | apache $ sudo echo '<FilesMatch "\.php$">' >> /etc/httpd/conf.d/php-fpm.conf
httpd_1  | apache $ sudo echo '    Require all granted' >> /etc/httpd/conf.d/php-fpm.conf
httpd_1  | apache $ sudo echo '    # Pick one of the following approaches' >> /etc/httpd/conf.d/php-fpm.conf
httpd_1  | apache $ sudo echo '    # Use the standard TCP socket' >> /etc/httpd/conf.d/php-fpm.conf
httpd_1  | apache $ sudo echo '    SetHandler "proxy:fcgi://php:9000"' >> /etc/httpd/conf.d/php-fpm.conf
httpd_1  | apache $ sudo echo '    # If your version of httpd is 2.4.9 or newer (or has the back-ported feature), you can use the unix domain socket' >> /etc/httpd/conf.d/php-fpm.conf
httpd_1  | apache $ sudo echo '    #SetHandler "proxy:unix:/path/to/app.sock|fcgi://localhost/:9000"' >> /etc/httpd/conf.d/php-fpm.conf
httpd_1  | apache $ sudo echo '</FilesMatch>' >> /etc/httpd/conf.d/php-fpm.conf
httpd_1  | [INFO] Adding custom include directory: /etc/apache-2.4
httpd_1  | apache $ sudo sed -i'' 's|^IncludeOptional[[:space:]]*conf\.d/.*$|IncludeOptional /etc/apache-2.4/*.conf|g' /etc/httpd/conf/httpd.conf
httpd_1  | [INFO] Starting Server version: Apache/2.4.6 (CentOS)
httpd_1  | apache $ sudo /usr/sbin/httpd -DFOREGROUND
php_1    | [INFO] Changing user 'devilbox' uid to: 1000
php_1    | root $ usermod -u 1000 devilbox
php_1    | usermod: no changes
php_1    | [INFO] Changing group 'devilbox' gid to: 1000
php_1    | root $ groupmod -g 1000 devilbox
php_1    | [WARN] $DOCKER_LOGS_ERROR not set.
php_1    | [WARN] Not logging errors to docker logs, using file inside container
php_1    | root $ chmod 0664 /var/log/php/www-error.log
php_1    | root $ chmod 0664 /var/log/php/php-fpm.err
php_1    | root $ chmod 0664 /var/log/php/www-slow.log
php_1    | root $ chown devilbox:devilbox /var/log/php/www-error.log
php_1    | root $ chown devilbox:devilbox /var/log/php/php-fpm.err
php_1    | root $ chown devilbox:devilbox /var/log/php/www-slow.log
php_1    | [WARN] $DOCKER_LOGS_ACCESS not set.
php_1    | [WARN] Not logging access to docker logs, using file inside container
php_1    | [WARN] $DOCKER_LOGS_XDEBUG not set.
php_1    | [WARN] Not logging xdebug to docker logs, using file inside container
php_1    | root $ chmod 0664 /var/log/php/www-access.log
php_1    | root $ chown devilbox:devilbox /var/log/php/www-access.log
php_1    | root $ chmod 0664 /var/log/php/xdebug.log
php_1    | root $ chown devilbox:devilbox /var/log/php/xdebug.log
php_1    | [INFO] Setting docker timezone to: Europe/Moscow
php_1    | root $ rm /etc/localtime
php_1    | root $ ln -s /usr/share/zoneinfo/Europe/Moscow /etc/localtime
php_1    | [INFO] Setting PHP: timezone=Europe/Moscow
php_1    | root $ sed -i'' 's|;*date.timezone[[:space:]]*=.*$|date.timezone = Europe/Moscow|g' /etc/php.ini
php_1    | [INFO] Docker date set to: Wed May 24 10:13:46 MSK 2017
php_1    | [INFO] Adding custom configuration files:
php_1    | root $ find /etc/php-custom.d -type f -iname "*.ini" -exec echo "Copying: {} to /etc/php.d/" \; -exec cp "{}" /etc/php.d/ \;
php_1    | Copying: /etc/php-custom.d/bitrix.ini to /etc/php.d/
php_1    | root $ find /etc/php.d -name '*.ini' -exec chmod 0644 {} \;
php_1    | [INFO] Setting PHP: xdebug.remote_enable=1
php_1    | root $ echo 'xdebug.remote_enable=1' >> /etc/php.d/15-xdebug.ini
php_1    | [INFO] Setting PHP: xdebug.remote_connect_back=0
php_1    | root $ echo 'xdebug.remote_connect_back=0' >> /etc/php.d/15-xdebug.ini
php_1    | [INFO] Setting PHP: xdebug.remote_port=9000
php_1    | root $ echo 'xdebug.remote_port=9000' >> /etc/php.d/15-xdebug.ini
php_1    | [INFO] Setting PHP: xdebug.remote_host=192.168.0.215
php_1    | root $ echo 'xdebug.remote_host=192.168.0.215' >> /etc/php.d/15-xdebug.ini
php_1    | [INFO] Setting PHP: xdebug.remote_log="/var/log/php/xdebug.log"
php_1    | root $ echo 'xdebug.remote_log="/var/log/php/xdebug.log"' >> /etc/php.d/15-xdebug.ini
php_1    | [INFO] Forwarding mysql:3306 to 127.0.0.1:3306 inside this docker.
php_1    | root $ /usr/bin/socat tcp-listen:3306,reuseaddr,fork tcp:mysql:3306 &
php_1    | [INFO] Forwarding pgsql:5432 to 127.0.0.1:5432 inside this docker.
php_1    | root $ /usr/bin/socat tcp-listen:5432,reuseaddr,fork tcp:pgsql:5432 &
php_1    | [INFO] Forwarding redis:6379 to 127.0.0.1:6379 inside this docker.
php_1    | root $ /usr/bin/socat tcp-listen:6379,reuseaddr,fork tcp:redis:6379 &
php_1    | [INFO] Forwarding memcd:11211 to 127.0.0.1:11211 inside this docker.
php_1    | root $ /usr/bin/socat tcp-listen:11211,reuseaddr,fork tcp:memcd:11211 &
bind_1   | [INFO] Adding wildcard DNS record: '*.loc' -> '172.16.238.11'
bind_1   | root $ echo 'include "/etc/bind/custom-named.conf.loc";' >> /etc/bind/named.conf
bind_1   | [INFO] Starting BIND 9.9.5
php_1    | [INFO] Enabling sending of emails.
php_1    | root $ chmod 0644 /var/mail/devilbox
php_1    | root $ chown devilbox:devilbox /var/mail/devilbox
php_1    | root $ sed -i'' 's/^inet_protocols.*/inet_protocols = ipv4/g' /etc/postfix/main.cf
php_1    | root $ echo 'virtual_alias_maps = pcre:/etc/postfix/virtual' >> /etc/postfix/main.cf
php_1    | root $ echo '/.*@.*/ devilbox' >> /etc/postfix/virtual
php_1    | root $ newaliases
php_1    | root $ postfix start
php_1    | root $ chown -R devilbox:devilbox /var/log/php
php_1    | root $ chmod 0755 /var/log/php
php_1    | root $ find /var/log/php -type f -exec chmod 0644 {} \;
php_1    | root $ rm -rf /var/lib/php/session
php_1    | root $ mkdir -p /var/lib/php/session
php_1    | root $ chown -R devilbox:devilbox /var/lib/php/session
php_1    | root $ chown -R devilbox:devilbox /home/devilbox
php_1    | root $ chown devilbox:devilbox /shared/httpd
php_1    | root $ echo ". /etc/bash_profile" >> /etc/bashrc
php_1    | [INFO] Starting PHP 7.0.19 (fpm-fcgi) (built: May  9 2017 16:02:34)
mysql_1  | [INFO] Setting docker timezone to: Europe/Moscow
mysql_1  | root $ rm /etc/localtime
mysql_1  | root $ ln -s /usr/share/zoneinfo/Europe/Moscow /etc/localtime
mysql_1  | [INFO] Docker date set to: Wed May 24 10:13:48 MSK 2017
mysql_1  | [INFO] Setting MySQL: [mysqld] general-log=1
mysql_1  | root $ touch /etc/my.cnf.d/logging.cnf
mysql_1  | root $ echo '[mysqld]' >> /etc/my.cnf.d/logging.cnf
mysql_1  | root $ echo 'general-log = 1' >> /etc/my.cnf.d/logging.cnf
mysql_1  | [INFO] Setting MySQL: [client] socket=/tmp/mysql/mysqld.sock
mysql_1  | root $ touch /etc/my.cnf.d/socket.cnf
mysql_1  | root $ echo '[client]' >> /etc/my.cnf.d/socket.cnf
mysql_1  | root $ echo 'socket = /tmp/mysql/mysqld.sock' >> /etc/my.cnf.d/socket.cnf
mysql_1  | [INFO] Setting MySQL: [mysql] socket=/tmp/mysql/mysqld.sock
mysql_1  | root $ echo '[mysql]' >> /etc/my.cnf.d/socket.cnf
mysql_1  | root $ echo 'socket = /tmp/mysql/mysqld.sock' >> /etc/my.cnf.d/socket.cnf
mysql_1  | [INFO] Setting MySQL: [mysqld] socket=/tmp/mysql/mysqld.sock
mysql_1  | root $ echo '[mysqld]' >> /etc/my.cnf.d/socket.cnf
mysql_1  | root $ echo 'socket = /tmp/mysql/mysqld.sock' >> /etc/my.cnf.d/socket.cnf
mysql_1  | root $ mkdir -p /tmp/mysql
mysql_1  | root $ chown mysql:mysql /tmp/mysql
mysql_1  | root $ chmod 0777 /tmp/mysql
mysql_1  | root $ chown -R mysql:mysql /var/lib/mysql/
mysql_1  | root $ chown -R mysql:mysql /var/lib/mysql
mysql_1  | root $ chown -R mysql:mysql /var/log/mysql
mysql_1  | root $ chown -R mysql:mysql /var/run/mysqld
mysql_1  | root $ chown -R mysql:mysql /var/sock/mysqld
mysql_1  | root $ chmod 0775 /var/lib/mysql/
mysql_1  | root $ chmod 0775 /var/lib/mysql
mysql_1  | root $ chmod 0775 /var/log/mysql
mysql_1  | root $ chmod 0775 /var/run/mysqld
mysql_1  | root $ chmod 0775 /var/sock/mysqld
mysql_1  | root $ find /var/log/mysql/ -type f -exec chmod 0664 {} \;
mysql_1  | [INFO] Found existing data directory. MySQL already setup.
mysql_1  | [INFO] Starting mysqld  Ver 5.7.18 for Linux on x86_64 (MySQL Community Server (GPL))
```
__log/php-fpm-7.0/php-fpm.err__ - empty

__log/php-fpm-7.0/www-error.log__:
```
[25-May-2017 12:15:56 Europe/Moscow] PHP Fatal error:  Uncaught UnexpectedValueException: Overloading of string functions using mbstring.func_overload is not supported by phpseclib. in /var/www/default/htdocs/vendor/phpmyadmin-4.7/vendor/phpseclib/phpseclib/phpseclib/bootstrap.php:11
Stack trace:
#0 /var/www/default/htdocs/vendor/phpmyadmin-4.7/vendor/composer/autoload_real.php(70): require()
#1 /var/www/default/htdocs/vendor/phpmyadmin-4.7/vendor/composer/autoload_real.php(60): composerRequire7033babd32da3410d35a338a5cac8c30('decc78cc4436b12...', '/var/www/defaul...')
#2 /var/www/default/htdocs/vendor/phpmyadmin-4.7/vendor/autoload.php(7): ComposerAutoloaderInit7033babd32da3410d35a338a5cac8c30::getLoader()
#3 /var/www/default/htdocs/vendor/phpmyadmin-4.7/libraries/common.inc.php(85): require_once('/var/www/defaul...')
#4 /var/www/default/htdocs/vendor/phpmyadmin-4.7/index.php(19): require_once('/var/www/defaul...')
#5 {main}
  thrown in /var/www/default/htdocs/vendor/phpmyadmin-4.7/vendor/phpseclib/phpseclib/phpseclib/bootstrap.php on line 11
```
__log/apache-2.4/devilbox-error.log__

```
[Tue May 23 17:15:35.338327 2017] [proxy_fcgi:error] [pid 90] [client 172.16.238.1:49140] AH01079: failed to make connection to backend: php
[Wed May 24 15:32:09.181636 2017] [proxy_fcgi:error] [pid 157] (70007)The timeout specified has expired: [client 172.16.238.1:38986] AH01075: Error dispatching request to :, referer: http://localhost/db_mysql.php
[Wed May 24 15:32:09.209849 2017] [proxy_fcgi:error] [pid 166] (70007)The timeout specified has expired: [client 172.16.238.1:39002] AH01075: Error dispatching request to :, referer: http://localhost/db_mysql.php
[Wed May 24 15:32:09.337765 2017] [proxy_fcgi:error] [pid 177] (70007)The timeout specified has expired: [client 172.16.238.1:38998] AH01075: Error dispatching request to :, referer: http://localhost/db_mysql.php

```
__log/apache-2.4/projects-error.log__
```
[Wed May 24 15:28:03.662956 2017] [proxy_fcgi:error] [pid 160] (70007)The timeout specified has expired: [client 172.16.238.1:36942] AH01075: Error dispatching request to :
[Wed May 24 17:24:20.294472 2017] [autoindex:error] [pid 174] [client 172.16.238.1:41980] AH01276: Cannot serve directory /shared/httpd/bitrix/htdocs/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive
[Wed May 24 17:24:27.366899 2017] [autoindex:error] [pid 174] [client 172.16.238.1:41980] AH01276: Cannot serve directory /shared/httpd/bitrix/htdocs/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive
```

__log/apache-2.4/error_log__
```
[Wed May 24 10:13:47.494601 2017] [lbmethod_heartbeat:notice] [pid 83] AH02282: No slotmem from mod_heartmonitor
[Wed May 24 10:13:47.506000 2017] [mpm_prefork:notice] [pid 83] AH00163: Apache/2.4.6 (CentOS) PHP/5.4.16 configured -- resuming normal operations
[Wed May 24 10:13:47.506039 2017] [core:notice] [pid 83] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
```

**Comment by cytopia** [comment]
Could you check out the release tag (you seem to be behind on git)

```
$ docker-compose stop
$ docker-compose rm
$ git checkout 0.9

# check differences
$ vimdiff .env env-example

$ docker-compose up
```

**Comment by fe3dback** [comment]
Nothing changes.

vimdiff show same result (like "diff .env env-example")

Now i run all containers:
```
❯ docker-compose up
Creating network "devilbox_app_net" with driver "bridge"
Creating devilbox_bind_1 ... 
Creating devilbox_bind_1 ... done
Creating devilbox_php_1 ... 
Creating devilbox_php_1 ... done
Creating devilbox_httpd_1 ... 
Creating devilbox_httpd_1 ... done
Creating devilbox_memcd_1 ... 
Creating devilbox_redis_1 ... 
Creating devilbox_pgsql_1 ... 
Creating devilbox_mysql_1 ... 
Creating devilbox_memcd_1
Creating devilbox_pgsql_1
Creating devilbox_mysql_1
Creating devilbox_redis_1 ... done
```

and get same error in http://localhost/vendor/phpmyadmin-4.7/index.php

**Comment by cytopia** [comment]
Could you see if `docker-compose pull` will give you newer container and also try out (only for testing) with php-5.6 and php-7.1

**Comment by fe3dback** [comment]
```
> docker-compose pull
...
Status: Downloaded newer image for cytopia/bind:latest
...
```
other containers has "up to date" status.
docker-compose pull not resolve issue.

Trying php7.1:
4.0 - not working (form visible, but before form showed many errors, like in comment 3)
4.7 (menu link to this version) - working without errors as expected

Trying php5.6:
4.0 - not working (same as 7.1)
4.7 (menu link to this version) - broken complete
```
 Fatal error: Uncaught exception 'UnexpectedValueException' with message 'Overloading of string functions using mbstring.func_overload is not supported by phpseclib.' in /var/www/default/htdocs/vendor/phpmyadmin-4.7/vendor/phpseclib/phpseclib/phpseclib/bootstrap.php on line 11
( ! ) UnexpectedValueException: Overloading of string functions using mbstring.func_overload is not supported by phpseclib. in /var/www/default/htdocs/vendor/phpmyadmin-4.7/vendor/phpseclib/phpseclib/phpseclib/bootstrap.php on line 11
Call Stack
#	Time	Memory	Function	Location
1	0.0025	264576	{main}( )	.../index.php:0
2	0.0227	266720	require_once( '/var/www/default/htdocs/vendor/phpmyadmin-4.7/libraries/common.inc.php' )	.../index.php:19
3	0.0304	268336	require_once( '/var/www/default/htdocs/vendor/phpmyadmin-4.7/vendor/autoload.php' )	.../common.inc.php:85
4	0.0316	270712	ComposerAutoloaderInit7033babd32da3410d35a338a5cac8c30::getLoader( )	.../autoload.php:7
5	0.0500	425760	composerRequire7033babd32da3410d35a338a5cac8c30( )	.../autoload_real.php:60
6	0.0545	426784	require( '/var/www/default/htdocs/vendor/phpmyadmin-4.7/vendor/phpseclib/phpseclib/phpseclib/bootstrap.php' )	.../autoload_real.php:70
```

**Comment by cytopia** [comment]
Ca you go to `http://localhost/info_php.php` and check the value of `mbstring.func_overload`

**Comment by cytopia** [comment]
Btw, what do you mean by

> 4.7 (menu link to this version) - broken complete

**Comment by cytopia** [comment]
Another thing that came to my mind.

When you do `docker-compose stop`.

Can you check afterwards if there are still container running (maybe from a different devilbox folder - in case you have multiple clonse).
```
docker ps
```

**Comment by fe3dback** [comment]
> Ca you go to http://localhost/info_php.php and check the value of mbstring.func_overload
oh, its my fault. I use custom php config with mbstring.func_overload = 2, several month already and forgot about it.. sorry.

phpadmin not support this overload, and fall with error.

**Comment by cytopia** [comment]
Alright. then it seems solved and I will close this issue.  Btw, what do you need this setting for? If it is a crucial one that you will need, I can hard-code it into phpmyadmin to be off and you can still have it on for your custom projects.

**Comment by fe3dback** [comment]
i do not use phpmyadmin, only want to help you with errors ).
adminer do all things well done.

// p.s. func_overload is requirement of popular shit driven russian cms (bitrix)

**Comment by cytopia** [comment]
Thanks for the info. First time I heard about shit driven development
