### ISSUE TITLE
Intranet not available when some php modules disabled or not compiled

### ISSUE THREAD

**Issue by llaville** [cytopia/devilbox#801]
### ISSUE TYPE

 - Bug Report

### Checklist

* [X] `.env` file is attached
* [X] `./check-config.sh` output is added below
* [ ] `docker-compose logs` output is added below
* [ ] `docker-compose.override.yml` is attached (if exists)
* [ ] Custom configs from `cfg/` dir are attached (if exist)
* [X] I've looked through the docs: https://devilbox.readthedocs.io/en/latest/
* [X] I've looked through existing issues: https://github.com/cytopia/devilbox/issues
* [X] I've read troubleshooting: https://devilbox.readthedocs.io/en/latest/support/troubleshooting.html

### OS / ENVIRONMENT

**1. Host operating system and version:** Windows 10 (20H2)
**2. (Windows only) Native Docker or Docker Toolbox:** Docker on WSL2
**3. Docker version:** Docker version 20.10.2, build 2291f61 
**4. Docker Compose version:**
**5. (Linux) Is SELinux enabled?:** NO
**6. What git commit hash are you on?:** cdfb55ec2d061bb20bb6aad1792034d995a855a2

### SUMMARY

Intranet is not available, and we get either blank page or PHP Fatal errors

### STEPS TO REPRODUCE

Start all containers and set localhost URL in your favorite browser

### EXPECTED BEHAVIOUR

Intranet should be available, even if some features are disabled

### ACTUAL BEHAVIOUR

Blank page or PHP Fatal Errors (depending of module disabled)

#### Start command

```
$ docker-compose up -d
```

#### Outputs

```bash
$ ./check-config.sh

# ==============================================================================
# Checking git
# ==============================================================================
[SUCC]  git is clean

# ==============================================================================
# Checking .env file
# ==============================================================================
[SUCC]  .env file exists
[SUCC]  .env file is readable
[SUCC]  All variables are present in .env file
[SUCC]  No variables is duplicated in .env file

# ==============================================================================
# Checking .env file values
# ==============================================================================
[SUCC]  All .env file variables have correct values

# ==============================================================================
# Checking required Devilbox core directories exist
# ==============================================================================
[SUCC]  All PHP cfg/ sub directories are present
[SUCC]  All PHP log/ sub directories are present
[SUCC]  All PHP mod/ sub directories are present
[SUCC]  All HTTPD cfg/ sub directories are present
[SUCC]  All HTTPD log/ sub directories are present

# ==============================================================================
# Checking devilbox core directory permissions
# ==============================================================================
[SUCC]  All devilbox directories have correct permissions
[SUCC]  All devilbox directories have correct uid
[SUCC]  All devilbox directories have correct gid

# ==============================================================================
# Checking devilbox core file permissions
# ==============================================================================
[SUCC]  All devilbox files have correct permissions
[SUCC]  All devilbox files have correct uid
[SUCC]  All devilbox files have correct gid

# ==============================================================================
# Checking projects permissions
# ==============================================================================
[SUCC]  All project dirs have correct permissions
[SUCC]  All project dirs have correct uid
[SUCC]  All project dirs have correct gid

# ==============================================================================
# Checking projects settings
# ==============================================================================
[SUCC]  All projects have valid DNS records
[SUCC]  All projects have valid HTTPD_DOCROOT_DIR

# ==============================================================================
# Checking customizations
# ==============================================================================
[INFO]  No custom configurations applied

# ==============================================================================
# SUMMARY
# ==============================================================================
[SUCC]  Found no errors
[INFO]  No custom configurations applied
[INFO]  Ensure to run 'docker-compose stop; docker-compose rm -f' on .env changes or custom configs
```

```bash
$ diff env-example .env

515c515
< PHP_MODULES_DISABLE=oci8,PDO_OCI,pdo_sqlsrv,sqlsrv,rdkafka,swoole
---
> PHP_MODULES_DISABLE=oci8,PDO_OCI,pdo_sqlsrv,sqlsrv,rdkafka,swoole,mongo,mongodb,redis,memcached,mysqli,pgsql
```

* When `mongo` (for PHP 5.2) or `mongodb` (for PHP 5.3 to 8.1) are disabled by configuration (or not compiled in `devilbox/docker-php-fpm` docker image), we get this error : 
```
Fatal error: Uncaught Error: Class 'MongoDB\Driver\Manager' not found in /var/www/default/include/lib/container/Mongo.php:47 Stack trace: #0 /var/www/default/include/lib/container/BaseClass.php(35): devilbox\Mongo->__construct('mongo', Array) #1 /var/www/default/config.php(161): devilbox\BaseClass::getInstance('mongo') #2 /var/www/default/htdocs/index.php(22): loadClass('Mongo') #3 {main} thrown in /var/www/default/include/lib/container/Mongo.php on line 47
```

* When `redis` is disable by configuration  (or not compiled in `devilbox/docker-php-fpm` docker image), we get this error : 
```
Fatal error: Uncaught Error: Class 'Redis' not found in /var/www/default/include/lib/container/Redis.php:41 Stack trace: #0 /var/www/default/include/lib/container/BaseClass.php(35): devilbox\Redis->__construct('redis', Array) #1 /var/www/default/config.php(146): devilbox\BaseClass::getInstance('redis') #2 /var/www/default/htdocs/index.php(20): loadClass('Redis') #3 {main} thrown in /var/www/default/include/lib/container/Redis.php on line 41
```

* When `memcache` and `memcached` are disabled by configuration  (or not compiled in `devilbox/docker-php-fpm` docker image), we still see info, DB panels while we should see an error or warning message

* When `mysqli` or `pgsql` are disable by configuration  (or not compiled in `devilbox/docker-php-fpm` docker image), we get blank page

**Comment by llaville** [comment]
PR to fix it will follow ...

**Comment by cytopia** [comment]
> When memcache and memcached are disabled by configuration (or not compiled in devilbox/docker-php-fpm docker image), we still see info, DB panels while we should see an error or warning message

I'm not so sure about this one.
Imo, If the container are started, they should also show up as started, regardless if PHP has a module for it.

**Comment by llaville** [comment]
Important info: PR 802 did not solve tools menus that have php modules requirements
